name: Generate Release Notes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Release Notes
      run: |
        npx semantic-release@17
        npx semantic-release-notes-generator@2.2.0 -o release_notes.md -l

    - name: Create Release
      uses: actions/create-release-action@v1
      with:
        tag-name: ${{ env.TAG_NAME }}
        release-name: "Release ${{ env.TAG_NAME }}"
        body-file-path: release_notes.md
        draft: true
        prerelease: false
