name: Create release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Create release
      uses: actions/create-release@v1
      with:
        tag_name: "v${{ env.TAG_NAME }}"
        release_name: "Release for version v${{ env.TAG_NAME }}"
        draft: false
        prerelease: false
