name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Release Drafter
      uses: release-drafter/action@v3
      with:
        tag_name: ${{ github.ref }}
