name: Create draft release

on:
  push:
    branches:
      - master

jobs:
  create-draft-release:
    runs-on: ubuntu-latest

    steps:
    - name: Create draft release
      uses: actions/create-release@v1
      with:
        tag_name: "v${{ env.TAG_NAME }}"
        release_name: "Draft release for version v${{ env.TAG_NAME }}"
        draft: true
        prerelease: true
        token: ${{ secrets.MY_AUTH }}
