name: Generate Release Notes

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Release Notes
      uses: actions/generate-release-notes-action@v1
      with:
        conventional-changelog-options: "--preset angular"
        file-name: CHANGELOG.md
        tag-from: ${{ env.TAG_FROM }}
        tag-to: ${{ env.TAG_TO }}
        context: ${{ env.GITHUB_CONTEXT }}

    - name: Update Release
      uses: actions/update-release-action@v1
      with:
        release-id: ${{ env.RELEASE_ID }}
        body-file-path: CHANGELOG.md
