name: Semantic Release

on:
  push:
    branches:
      - master

env:
  MY_AUTH_TOKEN: ${{ secrets.MY_AUTH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        uses: semantic-release/github-action@v1
        with:
          version: '^17.0.0'
          repository-dispatch: true
